/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_pkhope_picturepro_utils_PicUtils */

#ifndef _Included_me_pkhope_picturepro_utils_PicUtils
#define _Included_me_pkhope_picturepro_utils_PicUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_pkhope_picturepro_utils_PicUtils
 * Method:    getOriginalPixels
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_pkhope_picturepro_utils_PicUtils_getOriginalPixels
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
